### PR TITLE
feat: supports sass stylesheet and make isURL matching href="#.."

### PR DESCRIPTION
**Pull request by mindon**

### CODE REVIEW

**Comment by BjornTheProgrammer** [comment]
Looks good to me! Thank you for your contribution!

**Comment by mindon** [comment]
there's one issue when i use this with <https://github.com/mindon/bun.lit-and-mw3.demo>:

```shell
TypeError: undefined is not an object (evaluating 'G._Universe_findRule(L, W._primary)[B]')
      at _Parser_handleIdentifier (dist/index.js:8:101916)
      at _Parser_parse (dist/index.js:8:99960)
      at _Universe_evalInEnvironment (dist/index.js:8:94903)
      at toList$1$growable (dist/index.js:83:128503)
      at SourceFile$fromString (dist/index.js:28:5418)
      at SpanScanner$ (dist/index.js:51:3251)
      at ScssParser$0 (dist/index.js:61:29547)
      at BuiltInCallable$function0 (dist/index.js:51:36339)
      at call$0 (dist/index.js:202:23700)
      at dist/index.js:8:17290
```

if **bun-plugin-html** is built with **minify: false** - then no such error

**Comment by BjornTheProgrammer** [comment]
Hmm, do you mind creating a separate issue for this? We can track the issue there a bit better. I'll investigate to find out the issue.

**Comment by BjornTheProgrammer** [comment]
I've unpublished 2.2.0, since it seems like this was breaking every project if it relied on the minified build.

**Comment by BjornTheProgrammer** [comment]
I've began tracking this in #20

**Pull request merged**
